# Customer Shapping Behavior Analysis

*** Import necessery python lib and file ***

In [22]:
import pandas as pd
import numpy as np
import sqlalchemy
import pymysql

campaign_data=pd.read_csv(r"G:\code\Statistics\customer_shopping_behavior.csv")

In [23]:
campaign_data.head(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,Yes,14,Venmo,Weekly
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,Yes,49,Cash,Quarterly
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,Yes,19,Credit Card,Weekly
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,Yes,8,Venmo,Annually
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,Yes,4,Cash,Quarterly

Check for any Duplicate rows and remove or handle the duplicates

In [24]:
campaign_data.duplicated().sum()

np.int64(0)

Organize the column names for futher analysis

In [25]:
campaign_data.columns = campaign_data.columns.str.lower().str.replace(' ', '_')

In [26]:
campaign_data.describe(include='all')

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

Check for null values and replce it with median of respective groups

In [27]:
campaign_data.isnull().sum()

customer_id                0
age                        0
gender                     0
item_purchased             0
category                   0
purchase_amount_(usd)      0
location                   0
size                       0
color                      0
season                     0
review_rating             37
subscription_status        0
shipping_type              0
discount_applied           0
promo_code_used            0
previous_purchases         0
payment_method             0
frequency_of_purchases     0
dtype: int64

In [28]:
campaign_data.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [29]:
campaign_data["review_rating"]=campaign_data.groupby("category")["review_rating"].transform(lambda x: x.fillna(x.mean()))

In [30]:
campaign_data.rename(columns={"purchase_amunt_(usd)": "purchase_amount_(usd)"}, inplace=True)

Feature Engineering

In [31]:
label=['Young Adults', 'Adults', 'Middle Aged', 'Seniors']
campaign_data['age_group'] = pd.cut(campaign_data['age'], bins=[18, 25, 40, 60, 100], labels=label)

In [32]:
campaign_data[["age_group", "age"]].head(10)

      age_group  age
0   Middle Aged   55
1  Young Adults   19
2   Middle Aged   50
3  Young Adults   21
4   Middle Aged   45
5   Middle Aged   46
6       Seniors   63
7        Adults   27
8        Adults   26
9   Middle Aged   57

In [33]:
frequency_mapping = {"Fortnightly": 14, "Monthly": 30, "Weekly": 7, "Daily": 7,"Quarterly": 90, "Yearly": 365,"Bi-Weekly": 14,"Every 3 Months": 90,"Every 6 Months": 180,"Every 2 Weeks": 14,"Every 4 Weeks": 28,"Every 8 Weeks": 56,"Every 12 Weeks": 84}
campaign_data["purchase_frequency"] = campaign_data["frequency_of_purchases"].map(frequency_mapping)

In [34]:
campaign_data[["purchase_frequency", "frequency_of_purchases"]].head(10)

   purchase_frequency frequency_of_purchases
0                14.0            Fortnightly
1                14.0            Fortnightly
2                 7.0                 Weekly
3                 7.0                 Weekly
4                 NaN               Annually
5                 7.0                 Weekly
6                90.0              Quarterly
7                 7.0                 Weekly
8                 NaN               Annually
9                90.0              Quarterly

In [35]:
campaign_data[["discount_applied", "promo_code_used"]].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [36]:
(campaign_data["discount_applied"]==campaign_data["promo_code_used"]).all()

np.True_

In [37]:
campaign_data.drop(columns=["promo_code_used"], inplace=True)

In [39]:
campaign_data["previous_purchases_category"]=campaign_data["previous_purchases"].transform( lambda x: "New" if x<10 else ("Returning" if x<50 else "Loyal"))

In [40]:
campaign_data.head(10)

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency,previous_purchases_category
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle Aged,14.0,Returning
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adults,14.0,New
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle Aged,7.0,Returning
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adults,7.0,Returning
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle Aged,NaN,Returning
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,14,Venmo,Weekly,Middle Aged,7.0,Returning
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,49,Cash,Quarterly,Seniors,90.0,Returning
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,19,Credit Card,Weekly,Adults,7.0,Returning
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,8,Venmo,Annually,Adults,NaN,New
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,4,Cash,Quarterly,Middle Aged,90.0,New

Load the clearned and transformed data into the mysql DB named as campaign_analysis_db

In [41]:
import pymysql
from sqlalchemy import create_engine

# 1. Configuration variables
DB_USER = "root"
DB_PASS = "Yamaha@4320123"
DB_HOST = "localhost"
DB_NAME = "campaign_analysis_db"
TABLE_NAME = "cleaned_campaign_reports"

# 2. Step A: Create the Database (using PyMySQL)
try:
    # Connect to the server generally (without a DB target) to build the DB
    conn = pymysql.connect(host=DB_HOST, user=DB_USER, password=DB_PASS)
    with conn.cursor() as cursor:
        cursor.execute(f"CREATE DATABASE IF NOT EXISTS {DB_NAME}")
    conn.close()
    print(f"Database '{DB_NAME}' verified/created successfully.")
    
except Exception as e:
    print(f"Failed to create database: {e}")

# 3. Step B: Inject DataFrame into the DB (using SQLAlchemy & Pandas)
try:
    # Create the SQLAlchemy engine targeting our specific database
    # Format: mysql+pymysql://username:password@host/database_name
    engine = create_engine(f"mysql+pymysql://{DB_USER}:Yamaha%404320123@{DB_HOST}/{DB_NAME}")
    
    # Inject the data frame
    campaign_data.to_sql(
        name=TABLE_NAME,       # The name your SQL table will have
        con=engine,           # The SQLAlchemy connection engine
        if_exists='replace',   # Options: 'fail' (error if exists), 'replace' (drops & recreates), 'append' (adds rows)
        index=False           # Set to False so the pandas row numbers (0, 1, 2...) aren't uploaded as a separate column
    )
    print(f"Success! '{TABLE_NAME}' table created and populated in MySQL.")

except Exception as e:
    print(f"Data injection failed: {e}")

Database 'campaign_analysis_db' verified/created successfully.
Success! 'cleaned_campaign_reports' table created and populated in MySQL.